# Generated by Django 5.2.3 on 2025-06-24 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='initial_buying_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='added_by_user_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='addition_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='domain_user_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='product',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
